#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#api_refresh_token:
#    path: /api/v1/token/refresh
app.swagger_ui:
    path: /api/v1/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }